// Generated by CoffeeScript 1.9.2
(function() {
  var match;

  match = function($parse) {
    return {
      require: '?ngModel',
      restrict: 'A',
      link: function(scope, elem, attrs, ctrl) {
        var getMatchValue, matchGetter;
        if (!ctrl) {
          console.warn('Match validation requires ngModel to be on the element');
        }
        matchGetter = $parse(attrs.match);
        scope.$watch(getMatchValue, function() {
          return ctrl.$$parseAndValidate();
        });
        ctrl.$validators.match = function() {
          return ctrl.$viewValue === getMatchValue();
        };
        return getMatchValue = function() {
          match = matchGetter(scope);
          if (angular.isObject(match) && match.hasOwnProperty('$viewValue')) {
            match = match.$viewValue;
          }
          return match;
        };
      }
    };
  };

  angular.module('validation.match', []).directive('match', match);

}).call(this);

//# sourceMappingURL=match.js.map
