// Generated by CoffeeScript 1.9.2
(function() {
  describe("Match Directive", function() {
    var element, scope;
    element = void 0;
    scope = void 0;
    beforeEach(module("validation.match"));
    beforeEach(inject(function($compile, $rootScope) {
      scope = $rootScope.$new();
      return element = $compile('<form name="f"><input name="a" type="text" ng-model="a"></input><input name="b" type="text" ng-model="b" match="a"></input></form>')(scope);
    }));
    it("contains spec with an expectation", function() {
      scope.a = "A";
      scope.b = "B";
      scope.$digest();
      return expect(scope.f.b.$error.match).toBe(true);
    });
    return it("contains spec with an expectation", function() {
      scope.a = "A";
      scope.b = "A";
      scope.$digest();
      return expect(scope.f.b.$error.match).toBe(void 0);
    });
  });

}).call(this);

//# sourceMappingURL=match.js.map
