// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('settings.password', ['validation.match', 'ngMessages', 'ngResource']).config(function($httpProvider) {
    return $httpProvider.defaults.withCredentials = true;
  });

}).call(this);

//# sourceMappingURL=SettingsPassword.module.js.map
