require './registration/RegistrationApp'
require './player/PlayerApp'
require './goal/GoalApp'
require './error/ErrorApp'
require './headers/HeaderApp'
require './notification/NotificationApp'
require './feed/FeedApp'
require './listener/ListenerApp'
